// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seminario.Data;

#nullable disable

namespace Seminario.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251120225313_creat_table_agua")]
    partial class creat_table_agua
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Seminario.Core.Activo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Asset")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescripcionUbicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Equipment")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EsMarraneable")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaParcialoTotalmenteAerea")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaParcialoTotalmenteEnterrada")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Funcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("LatitudFin")
                        .HasColumnType("float");

                    b.Property<double?>("LatitudInicio")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<double?>("LongitudFin")
                        .HasColumnType("float");

                    b.Property<double?>("LongitudInicio")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SistemaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoActivoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SistemaId");

                    b.HasIndex("TipoActivoId");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("Seminario.Core.Campo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LatitudReferencia")
                        .HasColumnType("float");

                    b.Property<double?>("LongitudReferencia")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campos");
                });

            modelBuilder.Entity("Seminario.Core.MedicionComposicionAgua", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("AceiteAgua")
                        .HasColumnType("float");

                    b.Property<double?>("Acetate")
                        .HasColumnType("float");

                    b.Property<double?>("AcidoAcetico")
                        .HasColumnType("float");

                    b.Property<double?>("AcidoButirico")
                        .HasColumnType("float");

                    b.Property<double?>("AcidoFormico")
                        .HasColumnType("float");

                    b.Property<double?>("AcidoPropionico")
                        .HasColumnType("float");

                    b.Property<double?>("AcidoValerico")
                        .HasColumnType("float");

                    b.Property<double?>("Actinium")
                        .HasColumnType("float");

                    b.Property<double?>("Alcalinidad")
                        .HasColumnType("float");

                    b.Property<double?>("Aluminum")
                        .HasColumnType("float");

                    b.Property<double?>("Amide")
                        .HasColumnType("float");

                    b.Property<double?>("Amonio")
                        .HasColumnType("float");

                    b.Property<double?>("Arsenate")
                        .HasColumnType("float");

                    b.Property<double?>("Arsenite")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasAnaerobiasSesilesTotales")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasAnaerobiasTotales")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasHeterotrofasTotales")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasHeterotrofasTotalesSesiles")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasProductorasAcido")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasProductorasAcidoSesiles")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasSulfatoReductoras")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasSulfatoReductorasSesiles")
                        .HasColumnType("float");

                    b.Property<double?>("BacteriasTotales")
                        .HasColumnType("float");

                    b.Property<double?>("Barium")
                        .HasColumnType("float");

                    b.Property<double?>("Beryllium")
                        .HasColumnType("float");

                    b.Property<double?>("Bicarbonate")
                        .HasColumnType("float");

                    b.Property<double?>("Bisulfide")
                        .HasColumnType("float");

                    b.Property<double?>("Bisulfite")
                        .HasColumnType("float");

                    b.Property<double?>("Boron")
                        .HasColumnType("float");

                    b.Property<double?>("Bromate")
                        .HasColumnType("float");

                    b.Property<double?>("Bromide")
                        .HasColumnType("float");

                    b.Property<double?>("CO2")
                        .HasColumnType("float");

                    b.Property<double?>("Cadmium")
                        .HasColumnType("float");

                    b.Property<double?>("Calcium")
                        .HasColumnType("float");

                    b.Property<double?>("Carbonate")
                        .HasColumnType("float");

                    b.Property<double?>("Cesium")
                        .HasColumnType("float");

                    b.Property<double?>("Chlorate")
                        .HasColumnType("float");

                    b.Property<double?>("Chloride")
                        .HasColumnType("float");

                    b.Property<double?>("Chlorite")
                        .HasColumnType("float");

                    b.Property<double?>("Chromate")
                        .HasColumnType("float");

                    b.Property<double?>("ChromiumIII")
                        .HasColumnType("float");

                    b.Property<double?>("Citrate")
                        .HasColumnType("float");

                    b.Property<double?>("Cloruros")
                        .HasColumnType("float");

                    b.Property<double?>("CobaltII")
                        .HasColumnType("float");

                    b.Property<double?>("CobaltIII")
                        .HasColumnType("float");

                    b.Property<double?>("Conductividad")
                        .HasColumnType("float");

                    b.Property<double?>("CopperI")
                        .HasColumnType("float");

                    b.Property<double?>("CopperII")
                        .HasColumnType("float");

                    b.Property<double?>("Cyanate")
                        .HasColumnType("float");

                    b.Property<double?>("Cyanide")
                        .HasColumnType("float");

                    b.Property<double?>("DensidadDelAgua")
                        .HasColumnType("float");

                    b.Property<double?>("Dichromate")
                        .HasColumnType("float");

                    b.Property<double?>("DurezaCalcica")
                        .HasColumnType("float");

                    b.Property<double?>("DurezaMagnesica")
                        .HasColumnType("float");

                    b.Property<double?>("DurezaTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Ferricyanide")
                        .HasColumnType("float");

                    b.Property<string>("Ferrobacterias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Fluoride")
                        .HasColumnType("float");

                    b.Property<double?>("GoldI")
                        .HasColumnType("float");

                    b.Property<double?>("GoldIII")
                        .HasColumnType("float");

                    b.Property<double?>("H2S")
                        .HasColumnType("float");

                    b.Property<double?>("HierroSoluble")
                        .HasColumnType("float");

                    b.Property<double?>("HierroTotal")
                        .HasColumnType("float");

                    b.Property<double?>("Hydride")
                        .HasColumnType("float");

                    b.Property<double?>("Hydrogen")
                        .HasColumnType("float");

                    b.Property<double?>("HydrogenCarbonate")
                        .HasColumnType("float");

                    b.Property<double?>("HydrogenSulfate")
                        .HasColumnType("float");

                    b.Property<double?>("Hydroxide")
                        .HasColumnType("float");

                    b.Property<double?>("Hypochlorite")
                        .HasColumnType("float");

                    b.Property<double?>("Iodate")
                        .HasColumnType("float");

                    b.Property<double?>("Iodide")
                        .HasColumnType("float");

                    b.Property<double?>("IronII")
                        .HasColumnType("float");

                    b.Property<double?>("IronIII")
                        .HasColumnType("float");

                    b.Property<double?>("LeadI")
                        .HasColumnType("float");

                    b.Property<double?>("LeadII")
                        .HasColumnType("float");

                    b.Property<double?>("LeadIV")
                        .HasColumnType("float");

                    b.Property<double?>("Lithium")
                        .HasColumnType("float");

                    b.Property<double?>("Magnesium")
                        .HasColumnType("float");

                    b.Property<double?>("ManganeseII")
                        .HasColumnType("float");

                    b.Property<double?>("ManganeseIII")
                        .HasColumnType("float");

                    b.Property<double?>("MercuryI")
                        .HasColumnType("float");

                    b.Property<double?>("MercuryII")
                        .HasColumnType("float");

                    b.Property<double?>("NickelII")
                        .HasColumnType("float");

                    b.Property<double?>("NickelIV")
                        .HasColumnType("float");

                    b.Property<double?>("Nitrate")
                        .HasColumnType("float");

                    b.Property<double?>("Nitride")
                        .HasColumnType("float");

                    b.Property<double?>("Nitrite")
                        .HasColumnType("float");

                    b.Property<double?>("Nitritos")
                        .HasColumnType("float");

                    b.Property<double?>("O2")
                        .HasColumnType("float");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Oxalate")
                        .HasColumnType("float");

                    b.Property<double?>("Oxide")
                        .HasColumnType("float");

                    b.Property<double?>("PH")
                        .HasColumnType("float");

                    b.Property<double?>("Perchlorate")
                        .HasColumnType("float");

                    b.Property<double?>("Permanganate")
                        .HasColumnType("float");

                    b.Property<double?>("Phosphate")
                        .HasColumnType("float");

                    b.Property<double?>("Phosphide")
                        .HasColumnType("float");

                    b.Property<double?>("Phosphite")
                        .HasColumnType("float");

                    b.Property<double?>("Potassium")
                        .HasColumnType("float");

                    b.Property<string>("PuntoInformacionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("ResidualAmina")
                        .HasColumnType("float");

                    b.Property<double?>("ResidualBiocida")
                        .HasColumnType("float");

                    b.Property<double?>("ResidualEliminox")
                        .HasColumnType("float");

                    b.Property<double?>("ResidualInhibidorCorrosion")
                        .HasColumnType("float");

                    b.Property<double?>("ResidualInhibidorIncrustacion")
                        .HasColumnType("float");

                    b.Property<double?>("Silicate")
                        .HasColumnType("float");

                    b.Property<double?>("Silice")
                        .HasColumnType("float");

                    b.Property<double?>("Silver")
                        .HasColumnType("float");

                    b.Property<double?>("Sodium")
                        .HasColumnType("float");

                    b.Property<double?>("SolidosDisueltosTotales")
                        .HasColumnType("float");

                    b.Property<double?>("SolidosDisueltosVolatilesTotales")
                        .HasColumnType("float");

                    b.Property<double?>("SolidosSuspendidosTotales")
                        .HasColumnType("float");

                    b.Property<double?>("Strontium")
                        .HasColumnType("float");

                    b.Property<double?>("Sulfate")
                        .HasColumnType("float");

                    b.Property<double?>("Sulfatos")
                        .HasColumnType("float");

                    b.Property<double?>("Sulfide")
                        .HasColumnType("float");

                    b.Property<double?>("Sulfite")
                        .HasColumnType("float");

                    b.Property<double?>("Tan")
                        .HasColumnType("float");

                    b.Property<double?>("Tartrate")
                        .HasColumnType("float");

                    b.Property<double?>("TemperaturaMuestra")
                        .HasColumnType("float");

                    b.Property<double?>("Tetraborate")
                        .HasColumnType("float");

                    b.Property<double?>("Thiocyanate")
                        .HasColumnType("float");

                    b.Property<double?>("Thiosulfate")
                        .HasColumnType("float");

                    b.Property<double?>("TinII")
                        .HasColumnType("float");

                    b.Property<double?>("TinIV")
                        .HasColumnType("float");

                    b.Property<double?>("Vanadium")
                        .HasColumnType("float");

                    b.Property<double?>("Zinc")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PuntoInformacionId");

                    b.ToTable("MedicionesComposicionAgua");
                });

            modelBuilder.Entity("Seminario.Core.PuntoInformacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActivoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.ToTable("PuntosInformacion");
                });

            modelBuilder.Entity("Seminario.Core.Sistema", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CampoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampoId");

                    b.ToTable("Sistemas");
                });

            modelBuilder.Entity("Seminario.Core.TipoActivo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposActivo");
                });

            modelBuilder.Entity("Seminario.Core.Activo", b =>
                {
                    b.HasOne("Seminario.Core.Sistema", "Sistema")
                        .WithMany("Activos")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seminario.Core.TipoActivo", "TipoActivo")
                        .WithMany("Activos")
                        .HasForeignKey("TipoActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");

                    b.Navigation("TipoActivo");
                });

            modelBuilder.Entity("Seminario.Core.MedicionComposicionAgua", b =>
                {
                    b.HasOne("Seminario.Core.PuntoInformacion", "PuntoInformacion")
                        .WithMany("MedicionesComposicionAgua")
                        .HasForeignKey("PuntoInformacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoInformacion");
                });

            modelBuilder.Entity("Seminario.Core.PuntoInformacion", b =>
                {
                    b.HasOne("Seminario.Core.Activo", "Activo")
                        .WithMany("PuntosInformacion")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("Seminario.Core.Sistema", b =>
                {
                    b.HasOne("Seminario.Core.Campo", "Campo")
                        .WithMany("Sistemas")
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campo");
                });

            modelBuilder.Entity("Seminario.Core.Activo", b =>
                {
                    b.Navigation("PuntosInformacion");
                });

            modelBuilder.Entity("Seminario.Core.Campo", b =>
                {
                    b.Navigation("Sistemas");
                });

            modelBuilder.Entity("Seminario.Core.PuntoInformacion", b =>
                {
                    b.Navigation("MedicionesComposicionAgua");
                });

            modelBuilder.Entity("Seminario.Core.Sistema", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("Seminario.Core.TipoActivo", b =>
                {
                    b.Navigation("Activos");
                });
#pragma warning restore 612, 618
        }
    }
}
